apiVersion: v1
name: oauth2-proxy
description: Helm chart for oauth2-proxy
home: https://github.com/giantswarm/oauth2-proxy-app
version: "2.0.0"
appVersion: "7.1.3"
annotations:
  config.giantswarm.io/version: 1.x.x
icon: https://s.giantswarm.io/app-icons/oauth2-proxy/1/light.svg
