version: 2.1

orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-aws-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: aws-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-azure-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: azure-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-kvm-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: kvm-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-vmware-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: vmware-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-to-capa-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: capa-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: capz-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-to-gcp-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: gcp-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-to-vsphere-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: vsphere-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-cloud-director-app-collection
          context: architect
          app_name: oauth2-proxy
          app_namespace: monitoring
          app_collection_repo: cloud-director-app-collection
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
