version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-to-control-plane-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: oauth2-proxy
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
