version: 2.1

orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-giantswarm-app-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "oauth2-proxy"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-oauth2-proxy-to-aws-app-collection
          app_name: "oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-oauth2-proxy-to-azure-app-collection
          app_name: "oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-oauth2-proxy-to-kvm-app-collection
          app_name: "oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-oauth2-proxy-to-vmware-app-collection
          app_name: "oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-oauth2-proxy-to-capa-app-collection
          app_name: "oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
