version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-g8s-oauth2-proxy-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "g8s-oauth2-proxy"
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-g8s-oauth2-proxy-to-shared-app-collection
          app_name: "g8s-oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-g8s-oauth2-proxy-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-g8s-oauth2-proxy-to-aws-app-collection
          app_name: "g8s-oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-g8s-oauth2-proxy-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-g8s-oauth2-proxy-to-azure-app-collection
          app_name: "g8s-oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-g8s-oauth2-proxy-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-g8s-oauth2-proxy-to-kvm-app-collection
          app_name: "g8s-oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-g8s-oauth2-proxy-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
              
      - architect/push-to-app-collection:
          context: architect
          name: push-g8s-oauth2-proxy-to-vmware-app-collection
          app_name: "g8s-oauth2-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-g8s-oauth2-proxy-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
