port:
  name: oauth2-proxy
  port: 4180
  protocol: TCP

userID: 1000
groupID: 1000

registry:
  domain: docker.io

ingress:
  enabled: false

oauth2Proxy:
  cookie:
    expiry: 24h0m0s
    refresh: 0h60m0s
  emailDomain: "*"
  setAuthorizationHeader: true
  skipProviderButton: true
  oidc:
    issuerURL: ""
    loginURL: ""
    redeemURL: ""
    validateURL: ""
  providers:
  - id: "default"
    provider: "oidc"
    clientID: ""
    clientSecret: ""
    cookieSecret: ""
