{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- if eq 1 (len $.Values.oauth2Proxy.providers) }}
  name: {{ include "resource.default.name"  $ }}
{{- else }}
  name: {{ $provider.id }}-{{ include "resource.default.name"  $ }}
{{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- if gt (len $.Values.oauth2Proxy.providers) 1}}
    oauth2-proxy.provider: {{ $provider.id }}
    {{- end}}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "labels.selector" $ | nindent 6 }}
      {{- if gt (len $.Values.oauth2Proxy.providers) 1}}
      oauth2-proxy.provider: {{ $provider.id }}
      {{- end}}
  template:
    metadata:
      labels:
        {{- include "labels.common" $ | nindent 8 }}
        {{- if gt (len $.Values.oauth2Proxy.providers) 1}}
        oauth2-proxy.provider: {{ $provider.id }}
        {{- end}}
    spec:
      serviceAccountName: {{ include "resource.default.name" $ }}
      securityContext:
        runAsUser: {{ $.Values.userID }}
        runAsGroup: {{ $.Values.groupID }}
      containers:
      - image: {{ $.Values.registry.domain }}/giantswarm/oauth2-proxy:v7.1.3
        name: {{ include "resource.default.name" $ }}
        args:
        - --cookie-expire={{ $.Values.oauth2Proxy.cookie.expiry }}
        - --cookie-refresh={{ $.Values.oauth2Proxy.cookie.refresh }}
        - --email-domain={{ $.Values.oauth2Proxy.emailDomain }}
        - --http-address=0.0.0.0:4180
        - --provider={{ $provider.provider | default $.Values.oauth2Proxy.defaultProvider }}
        - --set-authorization-header={{ $.Values.oauth2Proxy.setAuthorizationHeader }}
        - --skip-provider-button={{ $.Values.oauth2Proxy.skipProviderButton }}
        {{- if $.Values.oauth2Proxy.oidc.issuerURL }}
        - --oidc-issuer-url={{ $.Values.oauth2Proxy.oidc.issuerURL }}
        {{- end }}
        {{- if $.Values.oauth2Proxy.oidc.loginURL }}
        - --login-url={{ $.Values.oauth2Proxy.oidc.loginURL }}
        {{- end }}
        {{- if $.Values.oauth2Proxy.oidc.redeemURL }}
        - --redeem-url={{ $.Values.oauth2Proxy.oidc.redeemURL }}
        {{- end }}
        {{- if $.Values.oauth2Proxy.oidc.profileURL }}
        - --profile-url={{ $.Values.oauth2Proxy.oidc.profileURL }}
        {{- end }}
        {{- if $.Values.oauth2Proxy.oidc.validateURL }}
        - --validate-url={{ $.Values.oauth2Proxy.oidc.validateURL }}
        {{- end }}
        - --upstream=file:///dev/null
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}
              {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
              key: client-id
              {{- else }}
              key: {{ $provider.id }}-client-id
              {{- end}}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}
              {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
              key: client-secret
              {{- else }}
              key: {{ $provider.id }}-client-secret
              {{- end}}
        {{- if $provider.cookieSecret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}
              {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
              key: cookie-secret
              {{- else }}
              key: {{ $provider.id }}-cookie-secret
              {{- end}}
        {{- end }}
        ports:
        - name: {{ $.Values.port.name }}
          containerPort: 4180
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 4180
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
{{- end }}
