{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "labels.selector" $ | nindent 6 }}
      oauth2-proxy.provider: {{ $provider.id }}
  template:
    metadata:
      labels:
        {{- include "labels.common" $ | nindent 8 }}
        oauth2-proxy.provider: {{ $provider.id }}
    spec:
      serviceAccountName: {{ include "resource.default.name" $ }}
      securityContext:
        {{- with $.Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      containers:
      - image: {{ $.Values.registry.domain }}/giantswarm/oauth2-proxy:v{{ $.Chart.AppVersion }}
        name: {{ include "resource.default.name" $ }}
        args:
        ## Cookie configuration options
        {{- with $provider.cookie.expiry }}
        - --cookie-expire={{ . }}
        {{- end }}
        {{- with $provider.cookie.name }}
        - --cookie-name={{ . }}
        {{- end }}
        {{- with $provider.cookie.refresh }}
        - --cookie-refresh={{ . }}
        {{- end }}
        {{- if $provider.cookie.secret }}
        - --cookie-secure=true
        {{- else }}
        - --cookie-secure=false
        {{- end }}

        # OIDC configuration options
        {{- with $provider.oidc.issuerURL }}
        - --oidc-issuer-url={{ . }}
        {{- end }}
        {{- with $provider.oidc.loginURL }}
        - --login-url={{ . }}
        {{- end }}
        {{- with $provider.oidc.profileURL }}
        - --profile-url={{ . }}
        {{- end }}
        {{- with $provider.oidc.redeemURL }}
        - --redeem-url={{ . }}
        {{- end }}
         {{- with $provider.oidc.validateURL }}
        - --validate-url={{ . }}
        {{- end }}

        {{- with $provider.emailDomain }}
        - --email-domain={{ . }}
        {{- end }}

        - --http-address=0.0.0.0:4180
        {{- if $.Values.serviceMonitor.enabled }}
        - --metrics-address=0.0.0.0:44180
        {{- end }}
       
        - --pass-access-token={{ $provider.passAccessToken }}
        - --pass-authorization-header={{ $provider.passAuthorizationHeader }}
        - --provider={{ $provider.provider }}
        - --set-authorization-header={{ $provider.setAuthorizationHeader }}
        - --set-xauthrequest={{ $provider.setXAuthRequest }}
        - --skip-jwt-bearer-tokens={{ $provider.skipJwtBearerTokens }}
        - --skip-provider-button={{ $provider.skipProviderButton }}

        {{- if $provider.upstream }}
        - --upstream={{ $provider.upstream }}
        {{- end }}

        {{- with $provider.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.oauth2Proxy.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
              key: "client-id"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
              key: "client-secret"
        {{- if $provider.cookie.secret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
              key: "cookie-secret"
        {{- end }}
        {{- with $provider.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with $.Values.oauth2Proxy.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: {{ $.Values.port.name }}
          containerPort: 4180
          protocol: TCP
        {{- if $.Values.serviceMonitor.enabled }}
        - containerPort: 44180
          protocol: TCP
          name: metrics
        {{- end }}
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ $.Values.port.name }}
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ $.Values.port.name }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          {{- with $.Values.containerSecurityContext }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
{{- end }}
