{{- if .Values.ingress.enabled }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: {{ .Values.ingress.letsencrypt.enabled | quote }}
    {{- if .Values.ingress.letsencrypt.enabled }}
    acme.cert-manager.io/http01-ingress-class: {{ .Values.ingress.className | quote }}
    {{- end }}
    {{- range $key, $val := .Values.ingress.extraAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
  - host: {{ $.Values.ingress.host }}
    http:
      paths:
      {{- range $provider := $.Values.oauth2Proxy.providers }}
      - backend:
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
            name: {{ include "resource.default.name"  $ }}
            {{- else }}
            name: {{ $provider.id }}-{{ include "resource.default.name"  $ }}
            {{- end}}
            port:
              number: {{ $.Values.port.port }}
          {{- else }}
          {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
          serviceName: {{ include "resource.default.name"  $ }}
          {{- else }}
          serviceName: {{ $provider.id }}-{{ include "resource.default.name"  $ }}
          {{- end}}
          servicePort: {{ $.Values.port.port }}
          {{- end }}
        {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
        path: /oauth2
        {{- else }}
        path: /{{ $provider.id }}/oauth2
        {{- end}}
        pathType: ImplementationSpecific
      {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $.Values.ingress.host }}
    secretName: {{ $.Values.ingress.certSecretName }}
  {{- end }}
{{- end }}
