{{- if and .Values.ingress.enabled $.Values.oauth2Proxy.providers }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingress.letsencrypt.enabled }}
    kubernetes.io/tls-acme: {{ .Values.ingress.letsencrypt.enabled | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /oauth2/$2
    {{- range $key, $val := .Values.ingress.extraAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ tpl . $ }}
    http:
      paths:
      {{- range $provider := $.Values.oauth2Proxy.providers }}
      - backend:
          service:
            name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
            port:
              number: {{ $.Values.port.port }}
        path: /oauth2/{{ $provider.id }}(/|$)(.*)
        pathType: ImplementationSpecific
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
      - {{ tpl . $ }}
      secretName: oauth-proxy-{{ regexReplaceAll "\\W+" (tpl . $) "-" }}
    {{- end }}
  {{- end }}
{{- end }}
