apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "resource.default.name" . }}-psp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostIPC: false
  hostPID: true
