{{- $singleProvider := (eq (len .Values.oauth2Proxy.providers) 1) -}}
{{- $providers := .Values.oauth2Proxy.providers }}
{{- $filteredProviders := list -}}
{{- range $providers -}}
{{- if not .existingSecret -}}
{{- $filteredProviders = append $filteredProviders . -}}
{{- end -}}
{{- end -}}
{{- $secretRequired := (gt (len $filteredProviders) 0) -}}
{{- if $secretRequired }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
data:
  {{- range $provider := $filteredProviders }}
  {{ ternary "" (printf "%s-" .id) $singleProvider }}client-id: {{ .clientID | b64enc | quote }}
  {{ ternary "" (printf "%s-" .id) $singleProvider }}client-secret: {{ .clientSecret | b64enc | quote }}
  {{- if .cookieSecret }}
  {{ ternary "" (printf "%s-" .id) $singleProvider }}cookie-secret: {{ .cookieSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
