{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
data:
  client-id: {{ .clientID | b64enc | quote }}
  client-secret: {{ .clientSecret | b64enc | quote }}
  {{- if .cookie.secret }}
  cookie-secret: {{ .cookie.secret | b64enc | quote }}
  {{- end }}
{{- end -}}
