{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
data:
  client-id: {{ $provider.clientID | b64enc | quote }}
  client-secret: {{ $provider.clientSecret | b64enc | quote }}
  {{- if $provider.cookieSecret }}
  cookie-secret: {{ $provider.cookieSecret | b64enc | quote }}
  {{- end }}
{{- end -}}
