apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
data:
  {{- range $provider := $.Values.oauth2Proxy.providers }}
  {{- if eq (len $.Values.oauth2Proxy.providers) 1}}
  client-id: {{ $provider.clientID | b64enc | quote }}
  client-secret: {{ $provider.clientSecret | b64enc | quote }}
  {{- if $provider.cookieSecret }}
  cookie-secret: {{ $provider.cookieSecret | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{ $provider.id }}-client-id: {{ $provider.clientID | b64enc | quote }}
  {{ $provider.id }}-client-secret: {{ $provider.clientSecret | b64enc | quote }}
  {{- if $provider.cookieSecret }}
  {{ $provider.id }}-cookie-secret: {{ $provider.cookieSecret | b64enc | quote }}
  {{- end }}
  {{- end}}
  {{- end }}
  
