{{- if $.Values.oauth2Proxy.providers }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
{{- end }}
