{{- if .Values.serviceMonitor.enabled }}
{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
spec:
  endpoints:
    - interval: {{ $.Values.serviceMonitor.interval }}
      path: /metrics
      port: metrics
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "labels.selector" $ | nindent 6 }}
      oauth2-proxy.provider: {{ $provider.id }}
{{- end }}
{{- end }}
