{{- if .Values.serviceMonitor.enabled }}
{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if eq 1 (len $.Values.oauth2Proxy.providers) }}
  name: {{ include "resource.default.name" $ }}
{{- else }}
  name: {{ $provider.id }}-{{ include "resource.default.name" $ }}
{{- end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- if gt (len $.Values.oauth2Proxy.providers) 1 }}
    oauth2-proxy.provider: {{ $provider.id }}
    {{- end }}
spec:
  endpoints:
    - interval: {{ $.Values.serviceMonitor.interval }}
      path: /metrics
      port: metrics
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "labels.selector" $ | nindent 6 }}
      {{- if gt (len $.Values.oauth2Proxy.providers) 1 }}
      oauth2-proxy.provider: {{ $provider.id }}
      {{- end}}
{{- end }}
{{- end }}
