{{- if $.Values.oauth2Proxy.providers }}
{{- range $provider := $.Values.oauth2Proxy.providers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: {{ $.Values.port.port }}
  {{- if $.Values.serviceMonitor.enabled }}
  - name: metrics
    port: 44180
    protocol: TCP
    targetPort: 44180
  {{- end }}
  selector:
    {{- include "labels.selector" $ | nindent 4 }}
    oauth2-proxy.provider: {{ $provider.id }}
{{- end }}
{{- end }}
