kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.port.port }}
      protocol: TCP
  egress:
  - {}  
  policyTypes:
  - Egress
  - Ingress
