kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      k8s-app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.port.port }}
      protocol: {{ .Values.port.protocol }}
  egress:
  - {}  
  policyTypes:
  - Egress
  - Ingress
