apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oauth2-proxy-secret
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: oauth2-proxy
data:
  client-id: {{ .Values.oauth2Proxy.clientID | b64enc | quote }}
  client-secret: {{ .Values.oauth2Proxy.clientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | b64enc | quote }}
